[package]
name = "sp-session"
version = "2.0.0-dev"
authors = ["Parity Technologies <admin@parity.io>"]
edition = "2018"
license = "GPL-3.0"
homepage = "https://substrate.dev"
repository = "https://github.com/paritytech/substrate/"
description = "Primitives for sessions"

[package.metadata.docs.rs]
targets = ["x86_64-unknown-linux-gnu"]

[dependencies]
sp-api = { version = "2.0.0-dev", default-features = false, path = "../api" }
sp-std = { version = "2.0.0-dev", default-features = false, path = "../std" }
sp-core = { version = "2.0.0-dev", default-features = false, path = "../core" }
sp-runtime = { version = "2.0.0-dev", optional = true, path = "../runtime" }

# x
codec = { package = "parity-scale-codec", version = "1.3.0", default-features = false }
hash-db = { version = "0.15.2", default-features = false }
trie-db = { version = "0.20.1", default-features = false }
sp-io ={ path = "../../primitives/io", default-features = false , version = "2.0.0-dev"}

[features]
default = [ "std" ]
std = [ "sp-api/std", "sp-std/std", "sp-runtime", "sp-core/std" ]
